version: "3.8"

services:
  lms-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Aa@123456"
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql

  lms-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__DefaultConnection: "Server=lms-db,1433;Database=PRN232_LAB_LMS;User Id=sa;Password=Aa@123456;TrustServerCertificate=True"
      Jwt__Issuer: "PRN232.LAB"
      Jwt__Audience: "PRN232.LAB"
      Jwt__Secret: "DO_NOT_USE_THIS_IN_PROD_CHANGE_ME_TO_A_LONG_RANDOM_SECRET"
      Jwt__AccessTokenMinutes: "60"
      Jwt__RefreshTokenDays: "7"
    depends_on:
      - lms-db

volumes:
  sqldata:
